
// First Name,Last Name,Registration No,Registration Type,Email Address,Phone Number,Age,State,District


const data=[
  {
      id:22,
      firstname:'prem',
      lastname:'kumar',
      registrationno:'12345',
      category:'abc',
      emailaddress:'prem@gmail.com',
      phonenumber:'1234567890',
      age:25,
      state:'delhi',
      district:'ncr',
      status:'reject'
},
{
  id:32,
  firstname:'Anand',
  lastname:'kumar',
  registrationno:'12345',
  category:'abc',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:25,
  state:'delhi',
  district:'ncr',
  status:'Approved'
},
{
  id:321,
  firstname:'Gowtham',
  lastname:'kumar',
  registrationno:'12345',
  category:'Speakers',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:25,
  state:'delhi',
  district:'ncr',
  status:'Approved'
},
{
  id:2114,
  firstname:'Ela',
  lastname:'kumar',
  registrationno:'12345',
  category:'Speakers',
  emailaddress:'ela@gmail.com',
  phonenumber:'1234567850',
  age:25,
  state:'delhi',
  district:'ncr',
  status:'Approved'
},
{
  id:2115,
  firstname:'logu',
  lastname:'kumar',
  registrationno:'125',
  category:'Media',
  emailaddress:'ela@gmail.com',
  phonenumber:'1234567890',
  age:25,
  state:'delhi',
  district:'sdsd',
  status:'Rejected'
},
{
  id:216,
  firstname:'Dinesh',
  lastname:'kumar',
  registrationno:'125',
  category:'Speakers',
  emailaddress:'dinesh@gmail.com',
  phonenumber:'1234567890',
  age:85,
  state:'Tamil Nadu',
  district:'ncr',
  status:'Rejected'
},
{
  id:217,
  firstname:'prem',
  lastname:'kumar',
  registrationno:'12345',
  category:'buyers',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:55,
  state:'delhi',
  district:'ncr',
  status:'Approved'
},
{
  id:218,
  firstname:'prem',
  lastname:'kumar',
  registrationno:'12345',
  category:'entrepreneur',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:35,
  state:'delhi',
  district:'ncr',
  status:'Approved'
},
{
  id:219,
  firstname:'prem',
  lastname:'kumar',
  registrationno:'12345',
  category:'Service',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:35,
  state:'Tamilnadu',
  district:'Chennai',
  status:'Approved'
},
{
  id:2110,
  firstname:'prem',
  lastname:'kumar',
  registrationno:'12345',
  category:'Trading',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:15,
  state:'Tamilnadu',
  district:'ncr'
},
{
  id:111,
  firstname:'prem',
  lastname:'kumar',
  registrationno:'12345',
  category:'Scalable Startups',
  emailaddress:'prem@gmail.com',
  phonenumber:'1234567890',
  age:15,
  state:'Tamilnadu',
  district:'Chennai'
},{
  id: 211,
  firstname: 'Prem',
  lastname: 'Kumar',
  registrationno: '10001',
  category: 'Scalable Startups',
  emailaddress: 'prem1@gmail.com',
  phonenumber: '9876543210',
  age: 15,
  state: 'Tamilnadu',
  district: 'Chennai'
},
{
  id: 212,
  firstname: 'Rajesh',
  lastname: 'Sharma',
  registrationno: '10002',
  category: 'Scalable Startups',
  emailaddress: 'rajesh2@gmail.com',
  phonenumber: '9876543211',
  age: 22,
  state: 'Kerala',
  district: 'Kochi'
},
{
  id: 213,
  firstname: 'Deepa',
  lastname: 'Nair',
  registrationno: '10003',
  category: 'Large Company',
  emailaddress: 'deepa3@gmail.com',
  phonenumber: '9876543212',
  age: 28,
  state: 'Karnataka',
  district: 'Bangalore'
},
{
  id: 214,
  firstname: 'Arun',
  lastname: 'Prasad',
  registrationno: '10004',
  category: 'Indian Market',
  emailaddress: 'arun4@gmail.com',
  phonenumber: '9876543213',
  age: 25,
  state: 'Andhra Pradesh',
  district: 'Vijayawada'
},
{
  id: 215,
  firstname: 'Meena',
  lastname: 'Ravi',
  registrationno: '10005',
  category: 'small',
  emailaddress: 'meena5@gmail.com',
  phonenumber: '9876543214',
  age: 35,
  state: 'Tamilnadu',
  district: 'Madurai'
},
{
  id: 216,
  firstname: 'Surya',
  lastname: 'Varma',
  registrationno: '10006',
  category: 'others',
  emailaddress: 'surya6@gmail.com',
  phonenumber: '9876543215',
  age: 40,
  state: 'Kerala',
  district: 'Thiruvananthapuram'
},
{
  id: 217,
  firstname: 'Lakshmi',
  lastname: 'Krishnan',
  registrationno: '10007',
  category: 'exhibitor',
  emailaddress: 'lakshmi7@gmail.com',
  phonenumber: '9876543216',
  age: 30,
  state: 'Karnataka',
  district: 'Mysore'
},
{
  id: 218,
  firstname: 'Vijay',
  lastname: 'Rao',
  registrationno: '10008',
  category: 'seminar attendee',
  emailaddress: 'vijay8@gmail.com',
  phonenumber: '9876543217',
  age: 32,
  state: 'Andhra Pradesh',
  district: 'Guntur'
},
{
  id: 219,
  firstname: 'Priya',
  lastname: 'Menon',
  registrationno: '10009',
  category: 'visitor',
  emailaddress: 'priya9@gmail.com',
  phonenumber: '9876543218',
  age: 27,
  state: 'Tamilnadu',
  district: 'Coimbatore'
},
{
  id: 210,
  firstname: 'Kiran',
  lastname: 'Das',
  registrationno: '10010',
  category: 'others',
  emailaddress: 'kiran10@gmail.com',
  phonenumber: '9876543219',
  age: 38,
  state: 'Kerala',
  district: 'Kollam'
},{
  id: 221,
  firstname: 'Prem',
  lastname: 'Kumar',
  registrationno: '10001',
  category: 'others',
  emailaddress: 'prem1@gmail.com',
  phonenumber: '9876543210',
  age: 15,
  state: 'Tamilnadu',
  district: 'Chennai'
},
{
  id: 222,
  firstname: 'Rajesh',
  lastname: 'Sharma',
  registrationno: '10002',
  category: 'visitor',
  emailaddress: 'rajesh2@gmail.com',
  phonenumber: '9876543211',
  age: 22,
  state: 'Kerala',
  district: 'Kochi'
},
{
  id: 223,
  firstname: 'Deepa',
  lastname: 'Nair',
  registrationno: '10003',
  category: 'exhibitor',
  emailaddress: 'deepa3@gmail.com',
  phonenumber: '9876543212',
  age: 28,
  state: 'Karnataka',
  district: 'Bangalore'
},
{
  id: 224,
  firstname: 'Arun',
  lastname: 'Prasad',
  registrationno: '10004',
  category: 'seminar attendee',
  emailaddress: 'arun4@gmail.com',
  phonenumber: '9876543213',
  age: 25,
  state: 'Andhra Pradesh',
  district: 'Vijayawada'
},
{
  id: 225,
  firstname: 'Meena',
  lastname: 'Ravi',
  registrationno: '10005',
  category: 'visitor',
  emailaddress: 'meena5@gmail.com',
  phonenumber: '9876543214',
  age: 35,
  state: 'Tamilnadu',
  district: 'Madurai'
},
{
  id: 226,
  firstname: 'Surya',
  lastname: 'Varma',
  registrationno: '10006',
  category: 'others',
  emailaddress: 'surya6@gmail.com',
  phonenumber: '9876543215',
  age: 40,
  state: 'Kerala',
  district: 'Thiruvananthapuram'
},
{
  id: 227,
  firstname: 'Lakshmi',
  lastname: 'Krishnan',
  registrationno: '10007',
  category: 'exhibitor',
  emailaddress: 'lakshmi7@gmail.com',
  phonenumber: '9876543216',
  age: 30,
  state: 'Karnataka',
  district: 'Mysore'
},
{
  id: 228,
  firstname: 'Vijay',
  lastname: 'Rao',
  registrationno: '10008',
  category: 'seminar attendee',
  emailaddress: 'vijay8@gmail.com',
  phonenumber: '9876543217',
  age: 32,
  state: 'Andhra Pradesh',
  district: 'Guntur'
},
{
  id: 229,
  firstname: 'Priya',
  lastname: 'Menon',
  registrationno: '10009',
  category: 'visitor',
  emailaddress: 'priya9@gmail.com',
  phonenumber: '9876543218',
  age: 27,
  state: 'Tamilnadu',
  district: 'Coimbatore'
},
{
  id: 110,
  firstname: 'Kiran',
  lastname: 'Das',
  registrationno: '10010',
  category: 'others',
  emailaddress: 'kiran10@gmail.com',
  phonenumber: '9876543219',
  age: 38,
  state: 'Kerala',
  district: 'Kollam'
},
{
  id: 111,
  firstname: 'Prem',
  lastname: 'Kumar',
  registrationno: '10001',
  category: 'others',
  emailaddress: 'prem1@gmail.com',
  phonenumber: '9876543210',
  age: 15,
  state: 'Tamilnadu',
  district: 'Chennai'
},
{
  id: 112,
  firstname: 'Rajesh',
  lastname: 'Sharma',
  registrationno: '10002',
  category: 'visitor',
  emailaddress: 'rajesh2@gmail.com',
  phonenumber: '9876543211',
  age: 22,
  state: 'Kerala',
  district: 'Kochi'
},
{
  id: 113,
  firstname: 'Deepa',
  lastname: 'Nair',
  registrationno: '10003',
  category: 'exhibitor',
  emailaddress: 'deepa3@gmail.com',
  phonenumber: '9876543212',
  age: 28,
  state: 'Karnataka',
  district: 'Bangalore'
},
{
  id: 114,
  firstname: 'Arun',
  lastname: 'Prasad',
  registrationno: '10004',
  category: 'seminar attendee',
  emailaddress: 'arun4@gmail.com',
  phonenumber: '9876543213',
  age: 25,
  state: 'Andhra Pradesh',
  district: 'Vijayawada'
},
{
  id: 115,
  firstname: 'Meena',
  lastname: 'Ravi',
  registrationno: '10005',
  category: 'visitor',
  emailaddress: 'meena5@gmail.com',
  phonenumber: '9876543214',
  age: 35,
  state: 'Tamilnadu',
  district: 'Madurai'
},
{
  id: 116,
  firstname: 'Surya',
  lastname: 'Varma',
  registrationno: '10006',
  category: 'others',
  emailaddress: 'surya6@gmail.com',
  phonenumber: '9876543215',
  age: 40,
  state: 'Kerala',
  district: 'Thiruvananthapuram'
},
{
  id: 117,
  firstname: 'Lakshmi',
  lastname: 'Krishnan',
  registrationno: '10007',
  category: 'exhibitor',
  emailaddress: 'lakshmi7@gmail.com',
  phonenumber: '9876543216',
  age: 30,
  state: 'Karnataka',
  district: 'Mysore'
},
{
  id: 1118,
  firstname: 'Vijay',
  lastname: 'Rao',
  registrationno: '10008',
  category: 'seminar attendee',
  emailaddress: 'vijay8@gmail.com',
  phonenumber: '9876543217',
  age: 32,
  state: 'Andhra Pradesh',
  district: 'Guntur'
},
{
  id: 119,
  firstname: 'Priya',
  lastname: 'Menon',
  registrationno: '10009',
  category: 'visitor',
  emailaddress: 'priya9@gmail.com',
  phonenumber: '9876543218',
  age: 27,
  state: 'Tamilnadu',
  district: 'Coimbatore'
},
{
  id: 110,
  firstname: 'Kiran',
  lastname: 'Das',
  registrationno: '10010',
  category: 'others',
  emailaddress: 'kiran10@gmail.com',
  phonenumber: '9876543219',
  age: 38,
  state: 'Kerala',
  district: 'Kollam'
}



]

export default data
